Manifest: !!python/unicode '/common/destiny_content/sqlite/en/world_sql_content_5c414893dac0deb1f473b74243454790.content'
MANIFEST_FILE: 'manifest/world_sql_content_5c414893dac0deb1f473b74243454790.content'
